### ISSUE TITLE
Starting..

### ISSUE THREAD

**Issue by Yashiroo** [jonsavage/VaultGUI#70] opened 2017-02-19 01:59 UTC
Hi,
I'm trying out this GUI for vault and upon starting it, i'm getting the following output:

```
[root@localhost VaultGUI]# npm run start

> VaultGUI@0.1.0 start /root/vault/VaultGUI
> babel app/js -d app/lib && electron app.js

app/js/components/AppBarComposition.jsx -> app/lib/components/AppBarComposition.js
app/js/components/Authentication.jsx -> app/lib/components/Authentication.js
app/js/components/ConnectionForm.jsx -> app/lib/components/ConnectionForm.js
app/js/components/GithubAuthentication.jsx -> app/lib/components/GithubAuthentication.js
app/js/components/Interact.jsx -> app/lib/components/Interact.js
app/js/components/Mounts.jsx -> app/lib/components/Mounts.js
app/js/components/Policies.jsx -> app/lib/components/Policies.js
app/js/components/RootTokenAuthentication.jsx -> app/lib/components/RootTokenAuthentication.js
app/js/components/SecretDeleter.jsx -> app/lib/components/SecretDeleter.js
app/js/components/SecretLister.jsx -> app/lib/components/SecretLister.js
app/js/components/SecretReader.jsx -> app/lib/components/SecretReader.js
app/js/components/SecretWriter.jsx -> app/lib/components/SecretWriter.js
app/js/components/Secrets.jsx -> app/lib/components/Secrets.js
app/js/components/Status.jsx -> app/lib/components/Status.js
app/js/components/Unseal.jsx -> app/lib/components/Unseal.js
app/js/components/UnsealProgressBar.jsx -> app/lib/components/UnsealProgressBar.js
app/js/components/UserPassAuthentication.jsx -> app/lib/components/UserPassAuthentication.js
app/js/containers/Page.jsx -> app/lib/containers/Page.js
app/js/index.js -> app/lib/index.js
/root/vault/VaultGUI/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

npm ERR! Linux 3.10.0-327.36.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! VaultGUI@0.1.0 start: `babel app/js -d app/lib && electron app.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the VaultGUI@0.1.0 start script 'babel app/js -d app/lib && electron app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the VaultGUI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel app/js -d app/lib && electron app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs VaultGUI
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls VaultGUI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/vault/VaultGUI/npm-debug.log
```

**Comment by jonsavage** [comment] 2017-02-19 02:25
Hey. Thanks for asking. Have you run an `npm install`?

**Comment by Yashiroo** [comment] 2017-02-19 16:40
Yes i have, as you can see in the logs, i have just installed node 7.4.0.
Any tips to debug this?

**Comment by jonsavage** [comment] 2017-02-19 22:03
Strange. I'm unable to reproduce locally (on a Mac nor Ubuntu.) I don't have access to a RHEL machine at the moment.

I did a little research and it looks like it might be an issue with the `electron-prebuilt` package. 
See https://github.com/electron-userland/electron-prebuilt/issues/92
I went ahead and updated it if you would like to give that a go. Make sure to reinstall your node modules locally since they aren't checked in.

**Comment by jonsavage** [comment] 2017-02-19 22:05
You also might have luck with:
`yum install libXstst.so.6`

**Comment by Yashiroo** [comment] 2017-02-20 00:38
I had to:
`yum install libXtst.x86_64`
but then this one appears instead:
`/root/vault/VaultGUI/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
`
So i had to install:
`libgconf-2.so.4`
`yum install GConf2`
Now i only have this:
```
npm ERR! Linux 3.10.0-327.36.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! VaultGUI@0.1.0 start: `babel app/js -d app/lib && electron app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the VaultGUI@0.1.0 start script 'babel app/js -d app/lib && electron app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the VaultGUI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel app/js -d app/lib && electron app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs VaultGUI
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls VaultGUI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/vault/VaultGUI/npm-debug.log
```

**Comment by jonsavage** [comment] 2017-02-20 13:50
Are you by any chance ssh'd into another machine or running this on  a core/server box without a desktop environment? 

I ask because that's the only way I can replicate your error.

**Comment by Yashiroo** [comment] 2017-02-20 13:54
I'm running this on a virtual machine and use ssh to access it, so if i understood you well then yes.
To my knowledge, i don't need a GUI on the OS to run something on node, correct me if i'm wrong.

**Comment by jonsavage** [comment] 2017-02-20 15:00
That's what your problem is. You don't need a desktop environment to run node but since this is an (Electron) desktop app it's trying to open up a window. You may be able to pipe the window to your client machine if you set up X. I'm not familiar with doing this on a RHEL machine and you may run into issues if your VM is a core/server box.

I'd recommend that you give it a go directly on a machine with a desktop environment.

**Comment by jonsavage** [comment] 2017-02-21 20:37
I'm going to go ahead and close this. 
I hope that worked for you. If not, please let me know here or open another issue.

**Closed as completed** 2017-02-21 20:38 UTC
